import 'package:flutter/foundation.dart';

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  static Assets? _instance;

  Assets._();

  factory Assets() {
    _instance ??= Assets._();
    return _instance!;
  }

    static const String welcome = 'assets/images/welcome.jpg';
}
