import 'package:flutter/foundation.dart';

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  static Assets? _instance;

  Assets._();

  factory Assets() {
    _instance ??= Assets._();
    return _instance!;
  }

    static const String welcome = 'assets/images/welcome.jpg';
    static const String protocolImage = 'assets/images/protocol_image.svg';
    static const String facebookIcon = 'assets/images/fb.svg';
    static const String instagramLogo = 'assets/images/insta.svg';
    static const String whatsappIcon = 'assets/images/Whts-App.svg';
    static const String backgroundImage = 'assets/images/background_imgae.png';
}
